backend:
    # Use netlify identity as backend
    name: git-gateway
    # branch: master
    branch: main
    ### enable below lines for github integration ###
    # name: github
    # repo: surjithctly/neat-starter
media_folder: "src/static/uploads"
public_folder: "/static/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
    - label: Pages
      name: pages
      files:
          - label: "Home"
            name: "home"
            file: "src/_data/homepage.yaml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Description, name: description, widget: string }
                - { label: Content, name: content, widget: markdown }
          - label: "Quienes somos"
            name: "quienes-somos"
            file: "src/_data/quienesSomos.yaml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Description, name: description, widget: string }
                - { label: Content, name: content, widget: markdown }
          - label: "Qué hacemos"
            name: "que-hacemos"
            file: "src/_data/queHacemos.yaml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Description, name: description, widget: string }
                - { label: Content, name: content, widget: markdown }
          - label: "Proyectos"
            name: "proyectos"
            file: "src/_data/proyectos.yaml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Description, name: description, widget: string }
                - { label: Content, name: content, widget: markdown }
          - label: "Contacto"
            name: "contacto"
            file: "src/_data/contacto.yaml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Description, name: description, widget: string }
                - { label: Form Title, name: formTitle, widget: string }
    - label: "Settings"
      name: "settings"
      editor:
          preview: false
      files:
          - label: "Navigation"
            name: "items"
            file: "src/_data/navigation.yaml"
            fields:
                - label: Nav Items
                  name: items
                  widget: list
                  allow_add: true
                  collapsed: false
                  fields:
                      - { label: Title, name: text, widget: string }
                      - { label: URL, name: url, widget: string }
          - label: "Quick Links"
            name: "links"
            file: "src/_data/quicklinks.yaml"
            fields:
                - label: Nav Items
                  name: links
                  widget: list
                  collapsed: false
                  fields:
                      - { label: Title, name: title, widget: string }
                      - { label: URL, name: url, widget: string }
                      - { label: Description, name: desc, widget: string }
          - label: "Meta Settings"
            name: "settings"
            file: "src/_data/settings.yaml"
            fields:
                - { label: Author, name: author, widget: string }
                - { label: URL, name: url, widget: string }
                - { label: Github, name: github, widget: string }
